services:
  - type: web
    name: coderefine-ai
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: 
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    startCommand: python app.py
    
